version: "3.9"
services:
  web:
    env_file:
      - app.env
    environment:
      - DEBUG=1
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
volumes:
  logvolume01: {}